# Generated by Django 3.1.4 on 2021-03-31 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=101, unique=True)),
                ('WholeSale_Price', models.IntegerField()),
                ('Retail_Price', models.IntegerField()),
                ('Picture', models.ImageField(upload_to='Pictures')),
                ('Item_type', models.CharField(choices=[['Shirts', 'Shirts'], ['Pants', 'Pants']], max_length=28)),
                ('Is_New_Arrival', models.BooleanField(default=True)),
                ('Upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
