# Generated by Django 3.1.4 on 2021-04-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Item'},
        ),
        migrations.AddField(
            model_name='items',
            name='Description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_type',
            field=models.CharField(choices=[['Shirts', 'Shirts'], ['Pants', 'Pants'], ['Towels', 'Towels'], ['Pillow_Covers', 'Pillows_Covers'], ['Bed_Sheets', 'Bed_Sheets'], ['Cotton_Sarees', 'Cotton_Sarees'], ['Cotton_Dress', 'Cotton_Dress Materials'], ['Door_Curtons', 'Door_Curtons']], max_length=28),
        ),
    ]
