# Generated by Django 3.1.4 on 2021-04-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0002_auto_20210401_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item'},
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_type',
            field=models.CharField(choices=[['Shirts', 'Shirts'], ['Pants', 'Pants'], ['Towels', 'Towels'], ['Pillow_Covers', 'Pillow_Covers'], ['Bed_Sheets', 'Bed_Sheets'], ['Cotton_Sarees', 'Cotton_Sarees'], ['Cotton_Dress', 'Cotton_Dress'], ['Door_Curtains', 'Door_Curtains']], max_length=28),
        ),
    ]
