# Generated by Django 3.1.4 on 2021-04-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0003_auto_20210401_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
