# Generated by Django 3.1.7 on 2021-05-13 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ItemsApp', '0004_auto_20210401_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_Item_no', models.AutoField(primary_key=True, serialize=False)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Item_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemsApp.items')),
            ],
        ),
    ]
