# Generated by Django 3.1.7 on 2021-05-13 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ItemsApp', '0005_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('Customer', 'Item_Id')},
        ),
    ]
